## 反汇编bomb

target:
	objdump -d bomb > bomb.s
	objdump -t bomb > bomb.help

## 分析bomb.s文件
## init
## errno
## strcpy, write, 
## phase_1
## phase_2
## ...
## 调试bomb文件
## gdb bomb
## 40143a explode_bomb
	chmod 777 bomb
## set breakpoint;
## b explode_bomb